- client/src/App.jsx
- client/src/index.jsx
i am testing how to add to our master branch
> added client folder with starter files _kh

- client/src/index.tsx
> Added test comment

- client/dist/index.html
- client/src/App.tsx
- client/src/index.tsx
- webpack.config.js
> witchcraft debunked

- .gitignore
- client/src/components/Overview/Features/ProductInfo/Subcomponents/ProductIdentifiers.tsx
- client/src/components/Overview/Features/ProductInfo/index.tsx
- client/src/components/Overview/OverviewStyles.css
- client/src/components/Overview/index.tsx
> Fixed Price, Did a little CSS

- client/src/components/Overview/Features/ImageGallery/Subcomponents/Image.tsx
- client/src/components/Overview/OverviewStyles.css
Small PR for image resizing to keep repo up to date
> Functional Image Resizing

- client/src/components/Questions-Answers/ExpandAndAdd.tsx
- client/src/components/Questions-Answers/QuestionForm.tsx
- client/src/components/Questions-Answers/QuestionFormStyles.css
- client/src/components/Questions-Answers/QuestionList.tsx
- client/src/components/QuestionsAndAnswers.tsx
- server.js
- server/Routers/qanda-routes.js
- server/helpers/qanda-helpers.js
- created question form
- should be able to do post requets with your AUTH key and with the hardcoded product_id # 37340
- added expres.json() middle ware to recived our json requests from axios
> Create question form

- client/src/App.tsx
- client/src/components/QARAWTEMPCSS.css
- client/src/components/Questions-Answers/AnswerForm.tsx
- client/src/components/Questions-Answers/ExpandAndAdd.tsx
- client/src/components/Questions-Answers/Question.tsx
- client/src/components/Questions-Answers/QuestionForm.tsx
- client/src/components/Questions-Answers/QuestionFormStyles.css
- client/src/components/Questions-Answers/QuestionList.tsx
- client/src/components/QuestionsAndAnswers.tsx
- server/Routers/products-routes.js
- server/Routers/qanda-routes.js
- server/helpers/qanda-helpers.js
- question form works
- answer form works
> Api updates from app

- client/src/components/Reviews-Ratings/RatingBreakdown.jsx
- client/src/components/Reviews-Ratings/ReviewsList.jsx
- client/src/components/Reviews-Ratings/ReviewsRatings.jsx
- client/src/components/Reviews-Ratings/Sorting.jsx
- client/src/components/Reviews-Ratings/helpers.js
Added dropdown with ability to sort list by three different factors
When reviewing, please look at the sortRelevance function in helpers file and let me know your thoughts. Relevance is supposed to balance a reviews helpfulness and its recentness.
> Sorting Feature

- .gitignore
- client/src/App.tsx
- client/src/components/Overview/Features/ImageGallery/Subcomponents/Image.tsx
- client/src/components/Overview/Features/ProductInfo/Subcomponents/ProductIdentifiers.tsx
- client/src/components/Overview/Features/ProductInfo/index.tsx
- client/src/components/Overview/index.tsx
> Quick fix for live product update data - got it working for overview

- client/src/components/QARAWTEMPCSS.css
> The cleanest branch so far

- client/src/App.tsx
- client/src/components/Reviews-Ratings/BreakdownComp.jsx
- client/src/components/Reviews-Ratings/NewReviewForm.jsx
- client/src/components/Reviews-Ratings/ProductBreakdown.jsx
- client/src/components/Reviews-Ratings/RatingBreakdown.jsx
- client/src/components/Reviews-Ratings/ReviewTile.jsx
- client/src/components/Reviews-Ratings/ReviewTileBody.jsx
- client/src/components/Reviews-Ratings/ReviewsList.jsx
- client/src/components/Reviews-Ratings/ReviewsRatings.css
- client/src/components/Reviews-Ratings/ReviewsRatings.jsx
- client/src/components/Reviews-Ratings/helpers.js
Added new form to add reviews - still need to create post route
Added Ben's star functionality to my components
Played around with css a bit
> Submit write review

- client/src/components/Reviews-Ratings/helpers.js
- client/src/components/Reviews-Ratings/spec/reviews_ratings.test.js
- package.json
Added test scripts for reviews, and updated npm test script to run jest
> added tests for functions in helpers.js

- client/dist/index.html
- client/src/components/Overview/Features/AddCart/CartForm.tsx
- client/src/components/Overview/Features/AddCart/index.tsx
- client/src/components/Overview/Features/StyleSelector/index.tsx
- client/src/components/Overview/OverviewStyles.css
- client/src/components/Overview/index.tsx
> Add to cart form and button

- client/src/App.tsx
- client/src/components/Reviews-Ratings/BreakdownComp.jsx
- client/src/components/Reviews-Ratings/NewReviewForm.jsx
- client/src/components/Reviews-Ratings/ProductBreakdown.jsx
- client/src/components/Reviews-Ratings/RatingBreakdown.jsx
- client/src/components/Reviews-Ratings/ReviewsList.jsx
- client/src/components/Reviews-Ratings/ReviewsRatings.css
- client/src/components/Reviews-Ratings/ReviewsRatings.jsx
- client/src/components/Reviews-Ratings/helpers.jsx
- client/src/components/Reviews-Ratings/spec/reviews_ratings.test.js
Added tests
Pointed to live data
Made small improvements to css and functionality
> Review tests

- client/src/components/Reviews-Ratings/NewReviewForm.jsx
- client/src/components/Reviews-Ratings/RatingBreakdown.jsx
- client/src/components/Reviews-Ratings/ReviewsList.jsx
- client/src/components/Reviews-Ratings/ReviewsRatings.jsx
- client/src/components/Reviews-Ratings/spec/reviews_ratings.test.js
- jest.config.js
- package-lock.json
- package.json
Added jest.config.js file that sets up testEnv and ignores things like css files.
Installed following in package.json:
"identity-obj-proxy": "^3.0.0",
"jest-environment-jsdom": "^29.6.2",
> created genuine test for react component

- client/src/components/Overview/Features/ProductInfo/Description.tsx
- client/src/components/Overview/Features/ProductInfo/ProductIdentifiers.tsx
- client/src/components/Overview/Features/ProductInfo/index.tsx
- client/src/components/Overview/OverviewStyles.css
- client/src/components/Overview/index.tsx
css mainly - changed position of description and slogan
> Overview formatting

- client/src/components/Reviews-Ratings/ReviewsList/Sorting.jsx
- client/src/components/Reviews-Ratings/ReviewsList/index.jsx
- client/src/components/Reviews-Ratings/index.jsx
- client/src/helpPlease.tsx
Fixed bugs in sorting filter:
- it now uses the API to sort by helpfulness and date
- relevance still controlled by custom function
- sorting now persists when filters applied
- cleaned up code associated with sorting
> Fix sort bug

- client/src/components/Reviews-Ratings/ReviewsList/ReviewTile.jsx
- server/Routers/reviews-routes.js
Set up put routes for helpfulness and reporting
> Put routes

- client/src/App.tsx
- client/src/components/Related/Links.tsx
- client/src/components/Related/List.tsx
> Completed List Functionality updatespage on click

- client/src/App.tsx
- client/src/components/Overview/Features/AddCart/CartForm.tsx
- client/src/components/Overview/Features/AddCart/index.tsx
- client/src/components/Overview/Features/ProductInfo/ProductIdentifiers.tsx
- client/src/components/Overview/Features/StyleSelector/index.tsx
- client/src/components/Overview/OverviewStyles.css
- client/src/components/Overview/index.tsx
- client/src/helpPlease.tsx
- package-lock.json
- package.json
- server.js
- server/Routers/cart-routes.js
- server/Routers/products-routes.js
- server/Routers/reviews-routes.js
npm install and then click my cart button for a cool lil party
> Squashed Cart Bugs, Added Required Field Functionality, added reward for adding to your cart

- client/src/App.tsx
- client/src/components/Overview/Features/AddCart/CartForm.tsx
- client/src/components/Overview/Features/ImageGallery/Image.tsx
- client/src/components/Overview/Features/ImageGallery/ImageCarousel.tsx
- client/src/components/Overview/Features/ImageGallery/index.tsx
- client/src/components/Overview/Features/ProductInfo/StarsAndReviews.tsx
- client/src/components/Overview/Features/ProductInfo/index.tsx
- client/src/components/Overview/OverviewStyles.css
- client/src/components/Overview/index.tsx
- client/src/helpPlease.tsx
don't move your mouse for a second when you load the site to help avoid bugs
> 0 to 100 for the image gallery carousel

- client/src/App.tsx
- client/src/components/Navbar/Navbar.tsx
- client/src/components/QuestionsAndAnswers/Features/Questions/AnswerPhoto.tsx
- client/src/components/QuestionsAndAnswers/QuestionsAndAnswers.styles.css
- client/src/components/Reviews-Ratings/RatingBreakdown/BreakdownComp.tsx
- client/src/components/Reviews-Ratings/ReviewsList/ReviewTile.tsx
- client/src/components/Reviews-Ratings/ReviewsList/ReviewTileBody.tsx
- client/src/components/Reviews-Ratings/ReviewsList/Sorting.tsx
- client/src/components/Reviews-Ratings/ReviewsList/index.tsx
- client/src/components/Reviews-Ratings/ReviewsRatings.css
- client/src/index.css
- server.js
- defaulted to dark mode
- edited all components to render nicely in dark mode (please check index.css [in react] to edit your components if you wish
- added animation to the chatgpt chatbox
- converted images with use state to utilize the reactjs-popup
> Start here aug18

- client/src/App.tsx
- client/src/components/Overview/Features/AddCart/index.tsx
- client/src/components/Overview/Features/ImageGallery/ImageCarousel.tsx
- client/src/components/Overview/Features/ImageGallery/index.tsx
- client/src/components/Overview/OverviewStyles.css
- client/src/components/Overview/index.tsx
- client/src/index.css
- package-lock.json
- package.json
fun with carousels - gave up on translations. Refactored some styling, added pretty alert button (thanks Khurram). In regards to the carousel - it ain't broke but it ain't pretty
> This PR has almost nothing to do with Add To Cart

- client/src/components/Reviews-Ratings/RatingBreakdown/index.tsx
- client/src/components/Reviews-Ratings/ReviewForm/index.tsx
- client/src/components/Reviews-Ratings/ReviewsList/Sorting.tsx
- client/src/components/Reviews-Ratings/ReviewsRatings.css
- client/src/helpPlease.tsx
Fixed my relevant sort function for good this time!
> Relevant refactor

- client/src/components/Overview/OverviewStyles.css
- client/src/components/Overview/index.tsx
- client/src/testing/overview.test.js
tested existence of all components/features and helper functions. We're at 52% tested
> Testing Testing
